from rct229.rule_engine.rule_base import RuleDefinitionBase
from rct229.rule_engine.rule_list_indexed_base import RuleDefinitionListIndexedBase
from rct229.rule_engine.ruleset_model_factory import produce_ruleset_model_description
from rct229.rulesets.ashrae9012019 import BASELINE_0
from rct229.rulesets.ashrae9012019.ruleset_functions.get_opaque_surface_type import (
    OpaqueSurfaceType as OST,
)
from rct229.rulesets.ashrae9012019.ruleset_functions.get_opaque_surface_type import (
    get_opaque_surface_type,
)
from rct229.schema.schema_enums import SchemaEnums
from rct229.utils.assertions import assert_
from rct229.utils.jsonpath_utils import find_all, find_one
from rct229.utils.pint_utils import ZERO

SUBSURFACE_CLASSIFICATION = SchemaEnums.schema_enums["SubsurfaceClassificationOptions"]
RULESET_MODEL = SchemaEnums.schema_enums["RulesetModelOptions2019ASHRAE901"]
ACCEPTABLE_FEN_PERCENTAGE_DIFFERENCE = 0.05


class PRM9012019Rule77j30(RuleDefinitionListIndexedBase):
    """Rule 1 of ASHRAE 90.1-2019 Appendix G Section 5 (Envelope)"""

    def __init__(self):
        super(PRM9012019Rule77j30, self).__init__(
            rmds_used=produce_ruleset_model_description(
                USER=True,
                BASELINE_0=True,
                BASELINE_90=True,
                BASELINE_180=True,
                BASELINE_270=True,
                PROPOSED=True,
            ),
            rmds_used_optional=produce_ruleset_model_description(
                BASELINE_90=True, BASELINE_180=True, BASELINE_270=True
            ),
            each_rule=PRM9012019Rule77j30.RMDRule(),
            index_rmd=BASELINE_0,
            id="5-1",
            description="The baseline building performance shall be generated by simulating the building with its actual orientation and again after rotating the entire building 90, 180, and 270 degrees, then averaging the results. "
            "Exceptions: "
            "1. If it can be demonstrated to the satisfaction of the rating authority that the building orientation is dictated bysite considerations. "
            "2. Buildings where the vertical fenestration area on each orientation varies by less than 5%.",
            ruleset_section_title="Envelope",
            standard_section="Table G3.1#5a baseline column",
            is_primary_rule=True,
            list_path="ruleset_model_descriptions[0]",
        )

    def create_data(self, context, data):
        rmd_b0 = context.BASELINE_0
        rmd_b90 = context.BASELINE_90
        rmd_b180 = context.BASELINE_180
        rmd_b270 = context.BASELINE_270
        rmd_p = context.PROPOSED
        rmd_u = context.USER

        bbp_values = set()
        for rmd in [rmd_u, rmd_b0, rmd_b90, rmd_b180, rmd_b270, rmd_p]:
            if rmd is not None:
                bbp = find_one(
                    "$.output.baseline_building_performance_energy_cost", rmd
                )
                if bbp is not None:
                    bbp_values.add(bbp)

        # --- BBP uniqueness check ---
        assert_(
            len(bbp_values) == 1,
            "Ruleset expects exactly one BBP value to be used in the project.",
        )

        return {"bbp_value": next(iter(bbp_values))}

    class RMDRule(RuleDefinitionListIndexedBase):
        def __init__(self):
            super(PRM9012019Rule77j30.RMDRule, self).__init__(
                rmds_used=produce_ruleset_model_description(
                    USER=True,
                    BASELINE_0=True,
                    BASELINE_90=True,
                    BASELINE_180=True,
                    BASELINE_270=True,
                    PROPOSED=True,
                ),
                rmds_used_optional=produce_ruleset_model_description(
                    BASELINE_90=True, BASELINE_180=True, BASELINE_270=True
                ),
                each_rule=PRM9012019Rule77j30.RMDRule.BuildingRule(),
                index_rmd=BASELINE_0,
                list_path="$.buildings[*]",
            )

        def create_data(self, context, data):
            rmd_b0 = context.BASELINE_0
            rmd_b90 = context.BASELINE_90
            rmd_b180 = context.BASELINE_180
            rmd_b270 = context.BASELINE_270

            baseline_0_total_annual_cost = None
            if rmd_b0 is not None:
                baseline_0_total_annual_cost = sum(
                    find_all(
                        "$.model_output.annual_source_results[*].annual_cost", rmd_b0
                    )
                )

            baseline_rotation_total_annual_costs = []
            for rmd in [rmd_b90, rmd_b180, rmd_b270]:
                if rmd is not None:
                    baseline_rotation_total_annual_costs.append(
                        sum(
                            find_all(
                                "$.model_output.annual_source_results[*].annual_cost",
                                rmd,
                            )
                        )
                    )

            return {
                "baseline_0_total_annual_cost": baseline_0_total_annual_cost,
                "baseline_rotation_total_annual_costs": baseline_rotation_total_annual_costs,
            }

        class BuildingRule(RuleDefinitionBase):
            def __init__(self):
                super(PRM9012019Rule77j30.RMDRule.BuildingRule, self).__init__(
                    rmds_used=produce_ruleset_model_description(
                        BASELINE_0=True,
                    ),
                    required_fields={
                        "$.building_segments[*].zones[*].surfaces[*]": ["azimuth"],
                    },
                    precision={
                        "percent_difference_max_min_fen_area_per_orientation": {
                            "precision": 0.01,
                            "unit": "",
                        }
                    },
                    manual_check_required_msg="Perform a manual check to verify whether Table G3.1#5a exception #2 is applicable, and it can be demonstrated that the building orientation is dictated by site considerations.",
                )

            def get_calc_vals(self, context, data=None):
                building_b0 = context.BASELINE_0

                # define a function to get the azimuth's corresponding key
                def get_key_for_azi(azi):
                    azi_value = azi.to("degrees").m
                    low_bound = azi_value - (azi_value % 3)
                    high_bound = low_bound + 3
                    return f"{low_bound}-{high_bound}"

                azimuth_fen_area_dict_b = {}
                for surface_b in find_all(
                    "$.building_segments[*].zones[*].surfaces[*]", building_b0
                ):
                    if get_opaque_surface_type(surface_b) == OST.ABOVE_GRADE_WALL:
                        surface_azimuth_b = surface_b["azimuth"]
                        total_surface_fenestration_area_b = ZERO.AREA
                        surface_azimuth_bin = get_key_for_azi(surface_azimuth_b)

                        if surface_azimuth_bin not in azimuth_fen_area_dict_b:
                            azimuth_fen_area_dict_b[surface_azimuth_bin] = ZERO.AREA

                        for subsurface_b in find_all("$.subsurfaces[*]", surface_b):
                            glazed_area_b = subsurface_b.get("glazed_area", ZERO.AREA)
                            opaque_area_b = subsurface_b.get("opaque_area", ZERO.AREA)

                            if (
                                subsurface_b["classification"]
                                == SUBSURFACE_CLASSIFICATION.DOOR
                            ):
                                if glazed_area_b > opaque_area_b:
                                    total_surface_fenestration_area_b += (
                                        glazed_area_b + opaque_area_b
                                    )
                            else:
                                total_surface_fenestration_area_b += (
                                    glazed_area_b + opaque_area_b
                                )
                        azimuth_fen_area_dict_b[
                            surface_azimuth_bin
                        ] += total_surface_fenestration_area_b

                max_fen_area_b = azimuth_fen_area_dict_b[
                    max(azimuth_fen_area_dict_b, key=azimuth_fen_area_dict_b.get)
                ]
                min_fen_area_b = azimuth_fen_area_dict_b[
                    min(azimuth_fen_area_dict_b, key=azimuth_fen_area_dict_b.get)
                ]

                percent_difference = max(
                    abs(max_fen_area_b - min_fen_area_b) / max_fen_area_b
                    if max_fen_area_b != ZERO.AREA
                    else 0.0,
                    abs(min_fen_area_b - max_fen_area_b) / min_fen_area_b
                    if min_fen_area_b != ZERO.AREA
                    else 0.0,
                )

                rotation_expected_b = (
                    percent_difference > ACCEPTABLE_FEN_PERCENTAGE_DIFFERENCE
                    or self.precision_comparison[
                        "percent_difference_max_min_fen_area_per_orientation"
                    ](
                        percent_difference.magnitude,
                        ACCEPTABLE_FEN_PERCENTAGE_DIFFERENCE,
                    )
                )

                baseline_0_total_annual_cost = data["baseline_0_total_annual_cost"]
                baseline_rotation_total_annual_costs = data[
                    "baseline_rotation_total_annual_costs"
                ]

                avg_baseline_total_annual_cost = (
                    (
                        baseline_0_total_annual_cost
                        + sum(baseline_rotation_total_annual_costs)
                    )
                    / (len(baseline_rotation_total_annual_costs) + 1)
                    if baseline_0_total_annual_cost
                    else None
                )

                return {
                    "rotation_expected_b": rotation_expected_b,
                    "bbp_value": data["bbp_value"],
                    "baseline_0_total_annual_cost": baseline_0_total_annual_cost,
                    "baseline_rotation_total_annual_costs": baseline_rotation_total_annual_costs,
                    "avg_baseline_total_annual_cost": avg_baseline_total_annual_cost,
                }

            def manual_check_required(self, context, calc_vals=None, data=None):
                rotation_expected_b = calc_vals["rotation_expected_b"]
                bbp_value = calc_vals["bbp_value"]
                baseline_0_total_annual_cost = calc_vals["baseline_0_total_annual_cost"]

                return rotation_expected_b and bbp_value == baseline_0_total_annual_cost

            def rule_check(self, context, calc_vals=None, data=None):
                rotation_expected_b = calc_vals["rotation_expected_b"]

                bbp_value = calc_vals["bbp_value"]
                baseline_0_total_annual_cost = calc_vals["baseline_0_total_annual_cost"]
                baseline_rotation_total_annual_costs = calc_vals[
                    "baseline_rotation_total_annual_costs"
                ]
                avg_baseline_total_annual_cost = calc_vals[
                    "avg_baseline_total_annual_cost"
                ]

                # ---------- CASES ----------
                # Case 1:
                # rotations expected AND BBP == avg of 4 baseline annual costs
                if (
                    rotation_expected_b
                    and len(baseline_rotation_total_annual_costs) == 3
                    and bbp_value == avg_baseline_total_annual_cost
                ):
                    return True

                # Case 2:
                # rotations NOT expected AND BBP == baseline_0 annual cost
                if (
                    not rotation_expected_b
                    and bbp_value == baseline_0_total_annual_cost
                ):
                    return True

                # Case 3:
                # rotations NOT expected AND BBP != baseline_0 annual cost
                if (
                    not rotation_expected_b
                    and bbp_value != baseline_0_total_annual_cost
                ):
                    return False

                # Case 4:
                # rotations expected AND BBP matches neither avg nor baseline_0
                else:
                    return False

            def get_fail_msg(self, context, calc_vals=None, data=None):
                rotation_expected_b = calc_vals["rotation_expected_b"]

                bbp_value = calc_vals["bbp_value"]
                baseline_0_total_annual_cost = calc_vals["baseline_0_total_annual_cost"]
                baseline_rotation_total_annual_costs = calc_vals[
                    "baseline_rotation_total_annual_costs"
                ]
                avg_baseline_total_annual_cost = calc_vals[
                    "avg_baseline_total_annual_cost"
                ]

                if (
                    rotation_expected_b
                    and len(baseline_rotation_total_annual_costs) < 3
                ):
                    return "Baseline building performance could not be validated because one or more of the required baseline rotation simulations (90, 180, or 270 degrees) did not include Source Result annual cost."
                elif (
                    rotation_expected_b and bbp_value != avg_baseline_total_annual_cost
                ):
                    return f"Baseline building performance energy cost ({bbp_value}) does not equal the average of the four baseline orientation annual costs ({avg_baseline_total_annual_cost})."
                elif (
                    not rotation_expected_b
                    and bbp_value != baseline_0_total_annual_cost
                ):
                    return f"Baseline building performance energy cost ({bbp_value}) does not equal the baseline (0 degree) annual cost ({baseline_0_total_annual_cost})."
                else:
                    return "Baseline building performance could not be validated."
