from pint import Quantity
from rct229.schema.schema_enums import SchemaEnums
from rct229.utils.jsonpath_utils import find_all
from rct229.utils.pint_utils import ZERO

LIGHTING_SPACE = SchemaEnums.schema_enums["LightingSpaceOptions2019ASHRAE901TG37"]

BUILDING_AREA_LOOKUP = {
    LIGHTING_SPACE.ATRIUM_LOW_MEDIUM: "UNDETERMINED",
    LIGHTING_SPACE.ATRIUM_HIGH: "UNDETERMINED",
    LIGHTING_SPACE.AUDIENCE_SEATING_AREA_AUDITORIUM: "UNDETERMINED",
    LIGHTING_SPACE.AUDIENCE_SEATING_AREA_CONVENTION_CENTER: "ALL_OTHER",
    LIGHTING_SPACE.AUDIENCE_SEATING_AREA_EXERCISE_CENTER: "UNDETERMINED",
    LIGHTING_SPACE.AUDIENCE_SEATING_AREA_GYMNASIUM: "UNDETERMINED",
    LIGHTING_SPACE.AUDIENCE_SEATING_AREA_MOTION_PICTURE_THEATER: "ALL_OTHER",
    LIGHTING_SPACE.AUDIENCE_SEATING_AREA_PENITENTIARY: "ALL_OTHER",
    LIGHTING_SPACE.AUDIENCE_SEATING_AREA_PERFORMING_ARTS_THEATER: "UNDETERMINED",
    LIGHTING_SPACE.AUDIENCE_SEATING_AREA_RELIGIOUS_FACILITY: "UNDETERMINED",
    LIGHTING_SPACE.AUDIENCE_SEATING_AREA_SPORTS_ARENA: "UNDETERMINED",
    LIGHTING_SPACE.AUDIENCE_SEATING_AREA_TRANSPORTATION_FACILITY: "ALL_OTHER",
    LIGHTING_SPACE.AUDIENCE_SEATING_AREA_ALL_OTHER: "UNDETERMINED",
    LIGHTING_SPACE.BANKING_ACTIVITY_AREA: "UNDETERMINED",
    LIGHTING_SPACE.CLASSROOM_LECTURE_HALL_TRAINING_ROOM_PENITENTIARY: "ALL_OTHER",
    LIGHTING_SPACE.CLASSROOM_LECTURE_HALL_TRAINING_ROOM_SCHOOL: "SCHOOL",
    LIGHTING_SPACE.CLASSROOM_LECTURE_HALL_TRAINING_ROOM_ALL_OTHER: "UNDETERMINED",
    LIGHTING_SPACE.CONFERENCE_MEETING_MULTIPURPOSE_ROOM: "UNDETERMINED",
    LIGHTING_SPACE.CONFINEMENT_CELLS: "ALL_OTHER",
    LIGHTING_SPACE.COPY_PRINT_ROOM: "UNDETERMINED",
    LIGHTING_SPACE.CORRIDOR_FACILITY_FOR_THE_VISUALLY_IMPAIRED: "UNDETERMINED",
    LIGHTING_SPACE.CORRIDOR_HOSPITAL: "HEALTHCARE_HOSPITAL",
    LIGHTING_SPACE.CORRIDOR_MANUFACTURING_FACILITY: "ALL_OTHER",
    LIGHTING_SPACE.CORRIDOR_ALL_OTHERS: "UNDETERMINED",
    LIGHTING_SPACE.COURT_ROOM: "OFFICE",
    LIGHTING_SPACE.COMPUTER_ROOM: "UNDETERMINED",
    LIGHTING_SPACE.DINING_AREA_PENITENTIARY: "ALL_OTHER",
    LIGHTING_SPACE.DINING_AREA_FACILITY_FOR_THE_VISUALLY_IMPAIRED: "UNDETERMINED",
    LIGHTING_SPACE.DINING_AREA_BAR_LOUNGE_OR_LEISURE_DINING: "RESTAURANT",
    LIGHTING_SPACE.DINING_AREA_CAFETERIA_OR_FAST_FOOD_DINING: "RESTAURANT",
    LIGHTING_SPACE.DINING_AREA_FAMILY_DINING: "RESTAURANT",
    LIGHTING_SPACE.DINING_AREA_ALL_OTHERS: "RESTAURANT",
    LIGHTING_SPACE.ELECTRICAL_MECHANICAL_ROOM: "UNDETERMINED",
    LIGHTING_SPACE.EMERGENCY_VEHICLE_GARAGE: "UNDETERMINED",
    LIGHTING_SPACE.FOOD_PREPARATION_AREA: "UNDETERMINED",
    LIGHTING_SPACE.GUEST_ROOM: "HOTEL_MOTEL",
    LIGHTING_SPACE.JUDGES_CHAMBERS: "OFFICE",
    LIGHTING_SPACE.DWELLING_UNIT: "MULTIFAMILY",
    LIGHTING_SPACE.LABORATORY_EXCEPT_IN_OR_AS_A_CLASSROOM: "ALL_OTHER",
    LIGHTING_SPACE.LAUNDRY_WASHING_AREA: "UNDETERMINED",
    LIGHTING_SPACE.LOADING_DOCK_INTERIOR: "UNDETERMINED",
    LIGHTING_SPACE.LOBBY_FACILITY_FOR_THE_VISUALLY_IMPAIRED: "UNDETERMINED",
    LIGHTING_SPACE.LOBBY_ELEVATOR: "UNDETERMINED",
    LIGHTING_SPACE.LOBBY_HOTEL: "HOTEL_MOTEL",
    LIGHTING_SPACE.LOBBY_MOTION_PICTURE_THEATER: "ALL_OTHER",
    LIGHTING_SPACE.LOBBY_PERFORMING_ARTS_THEATER: "ALL_OTHER",
    LIGHTING_SPACE.LOBBY_ALL_OTHERS: "UNDETERMINED",
    LIGHTING_SPACE.LOCKER_ROOM: "UNDETERMINED",
    LIGHTING_SPACE.LOUNGE_BREAKROOM_HEALTH_CARE_FACILITY: "HEALTHCARE_HOSPITAL",
    LIGHTING_SPACE.LOUNGE_BREAKROOM_ALL_OTHERS: "UNDETERMINED",
    LIGHTING_SPACE.OFFICE_ENCLOSED: "OFFICE",
    LIGHTING_SPACE.OFFICE_OPEN_PLAN: "OFFICE",
    LIGHTING_SPACE.PARKING_AREA_INTERIOR: "UNDETERMINED",
    LIGHTING_SPACE.PHARMACY_AREA: "UNDETERMINED",
    LIGHTING_SPACE.RESTROOM_FACILITY_FOR_THE_VISUALLY_IMPAIRED: "UNDETERMINED",
    LIGHTING_SPACE.RESTROOM_ALL_OTHERS: "UNDETERMINED",
    LIGHTING_SPACE.SALES_AREA: "RETAIL",
    LIGHTING_SPACE.SEATING_AREA_GENERAL: "UNDETERMINED",
    LIGHTING_SPACE.STAIRWELL: "UNDETERMINED",
    LIGHTING_SPACE.STORAGE_ROOM_HOSPITAL: "HEALTHCARE_HOSPITAL",
    LIGHTING_SPACE.STORAGE_ROOM_SMALL: "UNDETERMINED",
    LIGHTING_SPACE.STORAGE_ROOM_LARGE: "UNDETERMINED",
    LIGHTING_SPACE.VEHICULAR_MAINTENANCE_AREA: "ALL_OTHER",
    LIGHTING_SPACE.WORKSHOP: "UNDETERMINED",
    LIGHTING_SPACE.ASSISTED_LIVING_FACILITY_CHAPEL: "UNDETERMINED",
    LIGHTING_SPACE.ASSISTED_LIVING_FACILITY_RECREATION_ROOM_COMMON_LIVING_ROOM: "UNDETERMINED",
    LIGHTING_SPACE.CONVENTION_CENTER_EXHIBIT_SPACE: "ALL_OTHER",
    LIGHTING_SPACE.DORMITORY_LIVING_QUARTERS: "MULTIFAMILY",
    LIGHTING_SPACE.FIRE_STATION_SLEEPING_QUARTERS: "UNDETERMINED",
    LIGHTING_SPACE.GYMNASIUM_FITNESS_CENTER_EXERCISE_AREA: "UNDETERMINED",
    LIGHTING_SPACE.GYMNASIUM_FITNESS_CENTER_PLAYING_AREA: "UNDETERMINED",
    LIGHTING_SPACE.HEALTHCARE_FACILITY_EMERGENCY_ROOM: "HEALTHCARE_HOSPITAL",
    LIGHTING_SPACE.HEALTHCARE_FACILITY_EXAM_TREATMENT_ROOM: "HEALTHCARE_HOSPITAL",
    LIGHTING_SPACE.HEALTHCARE_FACILITY_MEDICAL_SUPPLY_ROOM: "HEALTHCARE_HOSPITAL",
    LIGHTING_SPACE.HEALTHCARE_FACILITY_NURSERY: "HEALTHCARE_HOSPITAL",
    LIGHTING_SPACE.HEALTHCARE_FACILITY_NURSES_STATION: "HEALTHCARE_HOSPITAL",
    LIGHTING_SPACE.HEALTHCARE_FACILITY_OPERATING_ROOM: "HEALTHCARE_HOSPITAL",
    LIGHTING_SPACE.HEALTHCARE_FACILITY_PATIENT_ROOM: "HEALTHCARE_HOSPITAL",
    LIGHTING_SPACE.HEALTHCARE_FACILITY_PHYSICAL_THERAPY_ROOM: "HEALTHCARE_HOSPITAL",
    LIGHTING_SPACE.HEALTHCARE_FACILITY_RECOVERY_ROOM: "HEALTHCARE_HOSPITAL",
    LIGHTING_SPACE.LIBRARY_READING_AREA: "UNDETERMINED",
    LIGHTING_SPACE.LIBRARY_STACKS: "UNDETERMINED",
    LIGHTING_SPACE.MANUFACTURING_FACILITY_DETAILED_MANUFACTURING_AREA: "ALL_OTHER",
    LIGHTING_SPACE.MANUFACTURING_FACILITY_EQUIPMENTROOM: "ALL_OTHER",
    LIGHTING_SPACE.MANUFACTURING_FACILITY_EXTRA_HIGH_BAY_AREA: "ALL_OTHER",
    LIGHTING_SPACE.MANUFACTURING_FACILITY_HIGH_BAY_AREA: "ALL_OTHER",
    LIGHTING_SPACE.MANUFACTURING_FACILITY_LOW_BAY_AREA: "ALL_OTHER",
    LIGHTING_SPACE.MUSEUM_GENERAL_EXHIBITION_AREA: "ALL_OTHER",
    LIGHTING_SPACE.MUSEUM_RESTORATION_ROOM: "ALL_OTHER",
    LIGHTING_SPACE.POST_OFFICE_SORTING_AREA: "ALL_OTHER",
    LIGHTING_SPACE.RELIGIOUS_FACILITY_FELLOWSHIP_HALL: "ALL_OTHER",
    LIGHTING_SPACE.RELIGIOUS_FACILITY_WORSHIP_PULPIT_CHOIR_AREA: "ALL_OTHER",
    LIGHTING_SPACE.RETAIL_FACILITIES_DRESSING_FITTING_ROOM: "RETAIL",
    LIGHTING_SPACE.RETAIL_FACILITIES_MALL_CONCOURSE: "RETAIL",
    LIGHTING_SPACE.SPORTS_ARENA_PLAYING_AREA_CLASS_I_FACILITY: "ALL_OTHER",
    LIGHTING_SPACE.SPORTS_ARENA_PLAYING_AREA_CLASS_II_FACILITY: "ALL_OTHER",
    LIGHTING_SPACE.SPORTS_ARENA_PLAYING_AREA_CLASS_III_FACILITY: "ALL_OTHER",
    LIGHTING_SPACE.SPORTS_ARENA_PLAYING_AREA_CLASS_IV_FACILITY: "UNDETERMINED",
    LIGHTING_SPACE.TRANSPORTATION_FACILITY_BAGGAGE_CAROUSEL_AREA: "ALL_OTHER",
    LIGHTING_SPACE.TRANSPORTATION_FACILITY_AIRPORT_CONCOURSE: "ALL_OTHER",
    LIGHTING_SPACE.TRANSPORTATION_FACILITY_TICKET_COUNTER: "ALL_OTHER",
    LIGHTING_SPACE.WAREHOUSE_STORAGE_AREA_MEDIUM_TO_BULKY_PALLETIZED_ITEMS: "WAREHOUSE",
    LIGHTING_SPACE.WAREHOUSE_STORAGE_AREA_SMALLER_HAND_CARRIED_ITEMS: "WAREHOUSE",
}


def get_zone_BPF_BAT(rmd: dict, zone_id: str) -> dict[str, Quantity]:
    """
     Get a dictionary of the BPF_BAT and areas for a given zone.

     Parameters
    ----------
    RMD: str, The ruleset model descriptions
    zone_id: str, The id of the zone

    Returns
    -------
    zone_BPF_BAT_dict: A dict for the zone that saves the BPF_BAT as keys and the areas as the values.
                       Example: {SCHOOL: 50000, UNDETERMINED: 2000}

    """

    zone_BPF_BAT_dict = {}
    for space in find_all(
        f'$.buildings[*].building_segments[*].zones[*][?(@.id = "{zone_id}")].spaces[*]',
        rmd,
    ):
        lighting_space_type = space.get("lighting_space_type", None)
        space_BPF_BAT = (
            "UNDETERMINED"
            if lighting_space_type is None
            else BUILDING_AREA_LOOKUP[lighting_space_type]
        )

        if space_BPF_BAT in zone_BPF_BAT_dict:
            zone_BPF_BAT_dict[space_BPF_BAT] += space.get("floor_area", ZERO.AREA)
        else:
            zone_BPF_BAT_dict[space_BPF_BAT] = space.get("floor_area", ZERO.AREA)

    return zone_BPF_BAT_dict
