openapi: 3.0.3
info:
  title: Ruleset Checking Tool Web Service API
  description: |-
  

  termsOfService: NA
  contact:
    email: weili.xu@pnnl.gov
  license:
    name: MIT
    url: https://github.com/pnnl/ruleset-checking-tool/blob/master/LICENSE
  version: 1.0.11
externalDocs:
  description: Find out more about Ruleset Checking Tool
  url: http://github.com/pnnl/ruleset-checking-tool
servers:
  - url: https://n3y4h0an6g.execute-api.us-west-2.amazonaws.com/prod
paths:
  /evaluate:
    post:
      summary: Run project evaluation on a set of RPDs
      description: This function runs the ruleset evaluation. Parameters required include a string for ruleset, a string for desired reports written in a comma separate format and a zip file that contains all the required RPDs for evaluation.
      parameters:
        - name: ruleset
          in: query
          description: ruleset tag, for example ashrae9012019.
          required: true
          schema:
            type: string
        - name: reports
          in: query
          description: list of reports string in a command separated format, for example ASHRAE9012019DetailReport,RawSummary.
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Evaluation'
        '400':
          description: Invalid request, missing data.
        '500':
          description: Internal Error.
  /rulesets:
    get:
      summary: Get a list of available ruleset tags
      description: Get a list of available ruleset tags
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RuleSetsCount'
        '500':
          description: Internal error.
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/InternalError'
  /rules:
    get:
      summary: Get number of rules implemented for a ruleset.
      description: Get the number of rules for a specified ruleset.
      parameters:
        - name: ruleset
          in: query
          description: ruleset tag, for example ashrae9012019.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RulesCount'
        '400':
          description: Invalid request, missing ruleset.
          content:
            application/json:
                schema:
                  $ref: '#/components/schemas/MissingDataError'
        '500':
          description: Internal error.
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/InternalError'
  /reports:
    get:
      summary: Get a list of available reports for a specified ruleset.
      description: Get a list of available reports for a specified ruleset.
      parameters:
        - name: ruleset
          in: query
          description: ruleset tag, for example ashrae9012019.
          required: true
          schema: 
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RuleSetReports'
        '400':
          description: Invalid request, missing ruleset.
          content:
            application/json:
                schema:
                  $ref: '#/components/schemas/MissingDataError'
        '500':
          description: Internal error.
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/InternalError'
components:
  schemas:
    Evaluation:
      type: object
      properties:
        sessionId:
          type: string
          example: "abc-def-efg"
    RuleSetsCount:
      type: object
      properties:
        num_rulesets:
          type: integer
          format: int64
          example: 10
        rulesets:
          type: array
          items:
            type: string
          example: ["ashrae9012019"]
    RulesCount:
      type: object
      properties:
        num_rules:
          type: integer
          format: int64
          example: 10
    RuleSetReports:
      type: object
      properties: 
        num_reports:
          type: integer
          format: int64
          example: 10
        reports:
          type: array
          items:
            type: string
          example: ["ASHRAE9012019DetailReport"]
    MissingDataError:
      type: object
      properties:
        message:
          type: string
          example: "Invalid request, missing rulesets."
    InternalError:
      type: object
      properties:
        message:
          type: string
          example: "Internal Error."