name: Publish to Test PyPI
on:
  push:
    tags:
      - '*.*.*'

jobs:
  test_pypi_release:
    name: Builds Using Poetry and Publishes to Test PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.release.tag_name}}
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install venv
        run: poetry install
      - name: Configure Poetry Repository
        run: poetry config repositories.testpypi https://test.pypi.org/legacy/
      - name: Configure Poetry For Test Publication
        run: poetry config pypi-token.testpypi "${{secrets.TEST_PYPI_API_KEY}}"
      - name: Compress json files for publication
        run: poetry run minify-jsons
      - name: Publish package
        run: poetry publish --build -r testpypi