# This workflow will release the branch to PYPI
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PYPI Release
on:
  release:
    types: [published]

# if merged, means the tests are passed from the CI process. In this action,
# it is only focus on publishing the package to PYPI
jobs:
  pypi_release:
    name: Builds Using Poetry and Publishes to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install venv
        run: poetry install
      - name: Configure Poetry For Publication
        run: poetry config pypi-token.pypi "${{secrets.PYPI_API_KEY}}"
      - name: Publish package
        run: poetry publish --build